version: '3.4'

services:
  web:
    image: wvxbs/curriculum
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/web
    restart: on-failure

  nginx:
    build: ./nginx
    ports:
    - '80:80'
    restart: on-failure
    depends_on:
      - web